---
title: "Linear Regression"
author: "Elsa Marques"
date: "12/11/2017"
output: 
  html_document:    
    code_folding: hide
    fig_height: 4
    fig_width: 6
    highlight: espresso
    number_sections: yes
    toc: yes
    toc_float: yes 
---

 > Visually clear and interesting explorations of the variables of interest in the data, from the point of view of your research question. Include interpretations of the distributions and relationships of the variables. Use captions to draw the reader’s focus on the interesting parts of your tables and graphics. (max 8 points)
 
 > Presentation of the results of your analysis including visualizations and summaries and a thorough interpretation of the results including a validation analysis of the method. (max 16 points)
 
 
## - Linear regresssion

Brief description of the method(s) you are using in your own words (max 3 points)

R makes it easy to graphically explore the validity of your model assumptions. If you give a linear model object as the first argument to the plot() function, the function automatically assumes you want diagnostic plots and will produce them. You can check the help page of plotting an lm object by typing ?plot.lm or help(plot.lm) to the R console.

```{r, echo=FALSE}

```

ggpairs(data = learning2014, mapping = aes(col = gender, alpha = 0.3), lower = list(combo = wrap("facethist", bins = 20)))


# plot with the 
p1 <- ggplot(data = learning2014, aes(x = Attitude, y = Points, col = gender))

# define the visualization type (points)
p2 <- p1 + geom_point()

# add a regression line
p3 <- p2 + geom_smooth(method = "lm")


#Linear model with three explanatory variables 
my_model <- lm(formula = Points ~ Attitude + stra + surf, data = learning2014)

#Summary of the linear model 
summary(my_model)



#Graphical model validation 
library(ggfortify)

autoplot(my_model, which= c(1, 2, 5)) +
     theme_bw()
     
     

