---
title: "Research topic"
author: "Elsa Marques"
date: "12/11/2017"
output: 
  html_document:
    code_folding: hide
    fig_height: 4
    fig_width: 6
    highlight: espresso
    number_sections: yes
    toc: yes
    toc_float: yes
---

### Author's Repository: https://elsamarques.github.io/IODS-final/ {.unnumbered}


# - Wrangling data 

## - Description of the original data set

 > The chosen data is originated from an enquiry about hobbies currently available in the FactoMiner library. The questionaire includes 18 questions regarding the type of hobbies undertaken by the enquired people. As suplemmentary questions: the amount of activities undertaken and four questions regarding the enquired people age, gender, profession and marital status were included. The data was collect from a total of 8403 individuals.

- Overview of the suplemmentary variables used to label the individuals: 
  - Gender / sex (male, female), 
  - Age (15-25, 26-35, 36-45, 46-55, 56-65, 66-75, 76-85, 86-100), 
  - Marital status (single, married, widowed,divorced, remarried), 
  - Profession (manual labourer, unskilled worker, technician, foreman, senior management, employee, other). 

## - [Data wrangling script file](https://github.com/ElsaMarques/IODS-final/blob/master/crerate%20IODS-final.R) 

- In order to perform the analysis I excluded from the data set all rows that included NA values; 

- All variables need to be factors in order to perform the MCA analysis 
    - "Number of activities" in hobbies was presented as intervals (quantitave variable); 

- For Linear regression analysis
  - Subsets of data were created in order to further validate the research hypothesis:
    - Hobbies divided by Generic, Sport, Artistic , Handcraft and Charity related categories 

- In order to perform LDA analysis:
    - The data needed to be scaled / standardized since the original data was not presenting the same variance range in all the variables; 
    - Test and train sets were created to validade the model; 
  
- Data was grouped by age ; gender ; profession and marital status (the extra categorical variables labeling the individuals)
  

# - Research topic and hypothesis 

 > For this exercise I am using the hobbies dataset that can be found in the FactoMineR libray. I will try to evaluate how different are the hobbies undertaken by gender, age, marital status and by the enquired professions. Will more demanding professions leave less space for hobbies or people will chose less time consuming hobbies? Is there some hobbies that are stereotypically associated with one or the other gender of the enquired people? Is age related with the amount and type of hobbies that inquired undertake?  
 
 
To explore if my hypothesis holds true, I explored the data trying to understand the following points: 

   - What kind of hobbies are more trendy among each Age, Gender, Profession or Marital Status group.
  
    - Linear regressions amongst the following variables:
  
      - Number of activities Vs Age
      - Number of activities Vs Gender
      - Number of activities Vs Profession 
      - Number of activities Vs Marital Status
      
      - Hobbies categories Vs Age 
      - Hobbies categories Vs Gender 
      - Hobbies categories Vs Profession
      - Hobbies categories Vs Marital Status
  
 
